### ISSUE TITLE
Write tests for `@tinyhttp/jsonp`

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#123]
Express tests: https://github.com/expressjs/express/blob/master/test/res.jsonp.js

Should be put in `__tests__/modules/jsonp.ts`

No need to write as many tests as in Express, if it hits 100% coverage, it's enough

**Comment by shubhi23994** [comment]
@talentlessguy  Thanks in advance for assigning this to me :)

**Comment by shubhi23994** [comment]
@talentlessguy  I have tried 2-3 things for callback tests but everything seems to give undefined on line 46 of jsonp/index.ts

1st thing:
`  it('should respond with jsonp', async () => {
      const { fetch, app, server } = InitAppAndTest((req, res) => jsonp(req, res, app)({ count: 1 }, {}))
      await fetch('/')
        .expect('Content-Type', 'application/json; charset=utf-8')
        .expect(200, /{"count":1}/)
    })`

This worked fine in case no callback is there but in case of callback it gives undefined for app[callbackName]

2nd method(took help from the readme and express example):
  `const app = new App()
    app.use(function (req, res) {
      res = jsonp(req, res, app)({ count: 1 }, {})
    })

    await fetch(app.listen(), '/?callback=something')
      .expect('Content-Type', 'text/javascript; charset=utf-8')
      .expect(200, /something\(\{"count":1\}\);/)`

Even this is causing the same issue as 1, giving undefined for app[callbackName]. I even tried app.set but that too is not working.
Can you help me in finding what am I doing wrong? Probably doing something silly!

**Comment by talentlessguy** [comment]
@shubhi23994 try without `InitAppAndTest`, just this:

```js
import { App } from '...'
import { jsonp } from '...'

const app = new App()
json(req, res, app)
```

**Comment by shubhi23994** [comment]
Tried this 

`const app = new App()
  app.use((req, res) => jsonp(req, res, app))`

But no luck!

The one that you posted was giving error on res and req and so had to put it inside app.use. But yea still the same issue

**Comment by talentlessguy** [comment]
@shubhi23994 

might be the issue with jsonp module then

will check it later

**Comment by talentlessguy** [comment]
@shubhi23994 can you try this?

https://github.com/talentlessguy/tinyhttp/tree/master/packages/jsonp#example

**Comment by shubhi23994** [comment]
I had tried this already and I kept getting this error `TypeError: Cannot destructure property 'escape' of '((cov_cpfoxmzi1(...).s[14]++) , opts)' as it is undefined.`

**Comment by talentlessguy** [comment]
@shubhi23994 which Node version are u using btw?

**Comment by shubhi23994** [comment]
Node version is: v14.13.0

**Comment by talentlessguy** [comment]
@shubhi23994 I think I just fixed it, check again please

**Comment by talentlessguy** [comment]
@shubhi23994 how are tests going ;D ?

**Comment by shubhi23994** [comment]
I saw the fix and seems to be fine but still not receiving this output like express. Some extra things are coming up. I am trying to figure them out. Will update you on this soon ☺️

**Comment by shubhi23994** [comment]
Hey! line 23 looks unreachable to me. Or maybe I am missing something. Can you have a look? I have raised the PR though covering all the other lines

**Comment by talentlessguy** [comment]
@shubhi23994 it's fine that 23 is unreachable, the coverage doesn't have to be 100%

and yes I'm taking a look now

**Comment by talentlessguy** [comment]
Closed via #134
