### ISSUE TITLE
Router methods hang if one is called after another

### ISSUE THREAD

**Issue by creepinson** [talentlessguy/tinyhttp#20]
'm having trouble with my custom async middleware...It seems to hang on loading the POST request and the logger middleware doesnt print anything related to that request. It also seems to block any app.use() lines after the line that is cuasing it to hang, which causes 404 to not work. I'm not sure what the problem is with my code (im using async/await with bcrypt and mongodb) but it shouldnt block other methods after it? What's weird is that app.get() lines that are BEFORE the problematic line work totally fine. I'll post my code here if needed but I'm not sure what is causing it to hang. I'm pretty sure ive handled all the errors AND changed some of the functions to async functions. I also checked that I'm sending a response with res.json() or res.send() so its not that im not sending anything...

heres my middleware file: https://hastebin.com/ifocicitem.js and heres where i use it: https://hastebin.com/juhovowuvo.coffeescript

**Comment by talentlessguy** [comment]
@creepinson I didn't read the whole code, but you probably forgot to put `next()` in your middlewares. In most cases, middleware hangs when you forget to switch to the next one.

It's mentioned in the guide: https://tinyhttp.v1rtl.site/learn#execution-order

**Comment by talentlessguy** [comment]
@creepinson I think I found the issue.

`@tinyhttp/jwt` is broken, it hangs infinitely for some reason. Here's an example of working async middleware: https://github.com/talentlessguy/tinyhttp/blob/57ba67c203fc0b24323a486f77daffceaf3696dd/examples/async/index.js

**Comment by talentlessguy** [comment]
if my assumption is incorrect, please let me know

**Comment by talentlessguy** [comment]
@creepinson that's hella weird

could you please try wrapping async await into try catches? maybe something will show up

**Comment by creepinson** [comment]
The thing is, I'm pretty sure I already have try catches on everything.. and if theres an error it should be sending it back to the client...

and i just tried with your async example in my code, it hangs as well on / 
```ts
		app.get("/", async (_, res, next) => {
			let file;

			try {
				file = await readFile(`${process.cwd()}/../test.txt`);
			} catch (e) {
				next!(e);
			}
			res.send(file?.toString());
		});
```

**Comment by talentlessguy** [comment]
@creepinson what Node version are u using?

I use 14.5.0 and it seems to be working just fine

**Comment by creepinson** [comment]
Oh, I'm using 12.18.0, but don't know why that would cause an issue.

**Comment by talentlessguy** [comment]
@creepinson hmmm interesting, maybe it's some bug that has been fixed in cutting edge versions.

could you please try with 14.5.0?

Using fnm for example:

```ts
# Install fnm
curl -fsSL https://github.com/Schniz/fnm/raw/master/.ci/install.sh | bash

# Install latest Node.js version
fnm install latest
fnm use latest
```

**Comment by creepinson** [comment]
Nope, it didn't fix it and I installed 14.5.0 with nvm and reinstalled pnpm.

**Comment by talentlessguy** [comment]
@creepinson I don't know then, it doesn't seem to be broken for me :shrug: 

I just went to `/tmp/app` and created this:

```js
// server.mjs
import { App } from '@tinyhttp/app'
import { readFile } from 'fs/promises'

const app = new App()

app.get('/', async (req, res, next) => {
    let file

    try {
        file = await readFile(`${process.cwd()}/package.json`)
    } catch (e) {
        next(e)
    }

    res.send(file.toString())
}).listen(3000)
```

and then tried to access `/`, it responded with the file, `/efewg` with 404

**Comment by creepinson** [comment]
Welp, here's the repo if you need it: https://github.com/creepinson/tinyhttp-monk-auth 
If you want to set it up you'll need a mongodb database.

It seems like the readFile part works but not the register or login so it must be something with await or something... but I used try and catch everywhere possible. idk what i did wrong :/

**Comment by talentlessguy** [comment]
@creepinson I just detected a bug: on first route non-match, e.g. accessing non existent route, it hangs, and after second time, it sends 404.

That's weird, and I'm trying to fix it rn

**Comment by talentlessguy** [comment]
@creepinson sorry for constantly pinging but, could you try again with with the `0.2.8` version?

**Comment by creepinson** [comment]
Oof.  I just tried it and it didnt seem to fix it... maybe it is something do to do with my code and not yours...

**Comment by talentlessguy** [comment]
@creepinson that's bad :(

sorry for the bugs, will be trying to fix them asap

**Comment by talentlessguy** [comment]
@creepinson okkaayy now, I think, I really fixed it. The problem was that a check that checks for middleware length didn't trigger because it contained the 404 handler in it. My bad. Now it should be working. Check it again please.

```sh
pnpm i @tinyhttp/app@0.2.10
```

**Comment by creepinson** [comment]
Welp it still happens.. i even tried just this
```ts
		app.post("/login", (req, res, next) => res.send("hello login"));
```
and then a 404 handler after it and doing /login hangs and doing /test (which should be a 404) hangs as well.

**Comment by talentlessguy** [comment]
@creepinson could you please setup a very small demo with only related to a problem things? So I can read the code easier and try to investigate :)

**Comment by talentlessguy** [comment]
ohhh one more bug unleashed. this is not working for some reason, sticks on a middleware and nothing happens after it. Probably related to previous bug. Working on finding a fix

**Comment by creepinson** [comment]
lol ok... 
well i was able to recreate it without using mongodb or anything:
https://github.com/creepinson/tinyhttp-example/blob/master/src/index.ts
If you go to /profile it works but posting /login does not.

**Comment by talentlessguy** [comment]
@creepinson I am a dumbass... during all this time, the `loop()` function just didn't execute because it was not in the end of `handle` function, but in `if...elses`

I hope this time it will work. Please try it. One. more. time.

```ts
pnpm i @tinyhttp/app@0.2.11
```

**Comment by creepinson** [comment]
![image](https://user-images.githubusercontent.com/11761863/87730321-41152b80-c77c-11ea-8e8a-408ad178544f.png)
YES! I think you finally solved it 😂
I just need to test it with the more complicated version that I made now...

**Comment by creepinson** [comment]
(node:33020) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

Well I think the original error is gone now though. but this  is interesting... it sends a 404 but i only have two places that could happen, one being at the end of the whole chain of app.*'s and then one in an auth middleware, but im not using that in /login which is causing the error.

**Comment by creepinson** [comment]
Hmm, i changed app.use() in my 404 error handler to app.get() and the error is different now.

**Comment by talentlessguy** [comment]
@creepinson glad to hear it's fixed! Even though the original issue was about another thing, I will just open new one for jwt specifically. And rename current one.
